language: java
sudo:     false
install:  true

jdk:
  - oraclejdk8

script:
  - ./dev.sh sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
